spring.application.name=capitec-transaction-aggregation 

# Server
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bankingdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Johannesburg
spring.datasource.username=root
spring.datasource.password=#1Buthelezi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=aggregation-group

spring.kafka.consumer.auto-offset-reset=earliest

aggregation.kafka.topic=transactions-topic

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
